#!/data/data/com.termux/files/usr/bin/sh
# install-poc.sh — Milestone 1 proof-of-concept.
#
# Installs Claude Code on stock Termux by:
#   1. Installing glibc-runner (grun) from tur-repo.
#   2. Running the official bootstrap.sh with the post-download
#      "claude install" step prefixed with grun.
#   3. Replacing the generated ~/.local/bin/claude launcher with a
#      wrapper that invokes the real binary under grun.
#
# Run inside Termux (NOT proot, NOT a real Linux distro):
#   sh scripts/install-poc.sh
#
# Re-runnable. Goal: `claude --version` exits zero.

set -eu

BOOTSTRAP_URL="https://downloads.claude.ai/claude-code-releases/bootstrap.sh"
STATE_DIR="$HOME/.termux-claude"
LAUNCHER="$HOME/.local/bin/claude"
LAUNCHER_BACKUP="$STATE_DIR/launcher.orig"
BOOTSTRAP_PATCHED="$STATE_DIR/bootstrap.patched.sh"
TERMUX_PREFIX="/data/data/com.termux/files/usr"

log() { printf '\033[1;34m[poc]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[poc] %s\033[0m\n' "$*" >&2; exit 1; }

# --- sanity ---------------------------------------------------------------
[ -d "$TERMUX_PREFIX" ] || die "not running inside Termux ($TERMUX_PREFIX missing)"
command -v pkg >/dev/null || die "pkg not found"

mkdir -p "$STATE_DIR" "$HOME/.local/bin"

# --- step 1: base packages ------------------------------------------------
# Termux bootstrap ships older libs; `pkg install` without a prior full
# upgrade can leave transitive deps ABI-mismatched (symptom seen:
# libngtcp2 referencing SSL symbols the shipped openssl lacks). Always
# full-upgrade first on a fresh Termux.
export DEBIAN_FRONTEND=noninteractive
log "syncing package index + full-upgrade (first-run sync; can take a minute)"
apt-get update -y -o Dpkg::Options::=--force-confnew
apt-get full-upgrade -y -o Dpkg::Options::=--force-confnew

log "installing curl, git, tur-repo"
apt-get install -y -o Dpkg::Options::=--force-confnew curl git tur-repo

# tur-repo drops a sources.list fragment that isn't indexed until the
# next `apt update`. Without this, `glibc-repo` is "unable to locate".
log "refreshing index for tur-repo"
apt-get update -y

# glibc-runner lives in a separate repo (termux-glibc). `glibc-repo` is
# the tiny shim in tur-repo that adds that repo's sources.list fragment
# and runs `apt update` from its postinst.
log "installing glibc-repo (adds termux-glibc sources)"
apt-get install -y -o Dpkg::Options::=--force-confnew glibc-repo

log "installing glibc-runner (grun)"
apt-get install -y -o Dpkg::Options::=--force-confnew glibc-runner

command -v grun >/dev/null || die "grun not on PATH after glibc-runner install"

# --- step 2: fetch + patch bootstrap.sh -----------------------------------
log "fetching bootstrap.sh"
curl -fsSL "$BOOTSTRAP_URL" -o "$BOOTSTRAP_PATCHED"

log "patching bootstrap.sh to run installer under grun"
# The target line near the end of upstream bootstrap.sh:
#     "$binary_path" install ${TARGET:+"$TARGET"}
# Prefix it with grun so the native binary can execute on Termux.
if ! grep -q '"$binary_path" install' "$BOOTSTRAP_PATCHED"; then
    die "bootstrap.sh format changed; expected '\"\$binary_path\" install' line"
fi
sed -i 's#"\$binary_path" install#grun "$binary_path" install#' "$BOOTSTRAP_PATCHED"

# --- step 3: run the patched bootstrap ------------------------------------
log "running patched bootstrap.sh (this downloads + installs Claude Code)"
bash "$BOOTSTRAP_PATCHED"

[ -f "$LAUNCHER" ] || die "bootstrap did not create $LAUNCHER"

# --- step 4: find the real binary & swap the launcher ---------------------
log "locating installed claude binary"
# `claude install` drops the native binary at ~/.local/share/claude/versions/<ver>
# and makes ~/.local/bin/claude a symlink to it.
if [ -L "$LAUNCHER" ]; then
    REAL_BIN="$(readlink -f "$LAUNCHER")"
else
    # Fallback: glob the versions dir for the newest ELF by filename version.
    REAL_BIN="$(
        find "$HOME/.local/share/claude/versions" -maxdepth 1 -type f \
            2>/dev/null | sort -V | tail -n1
    )"
fi
[ -n "${REAL_BIN:-}" ] && [ -x "$REAL_BIN" ] \
    || die "could not locate the installed claude binary under ~/.local/share/claude/versions"
log "real binary: $REAL_BIN"

log "saving original symlink target to $LAUNCHER_BACKUP"
printf '%s\n' "$REAL_BIN" > "$LAUNCHER_BACKUP"

log "replacing symlink with grun wrapper at $LAUNCHER"
rm -f "$LAUNCHER"
cat > "$LAUNCHER" <<EOF
#!$TERMUX_PREFIX/bin/sh
# Generated by claude-termux install-poc.sh — wraps the native Claude Code
# binary with glibc-runner (grun) so it can execute on Termux's bionic libc.
# NOTE: \`claude update\` will overwrite this file by restoring the symlink.
# Re-run install-poc.sh after any update.
exec grun "$REAL_BIN" "\$@"
EOF
chmod +x "$LAUNCHER"

# --- step 5: PATH --------------------------------------------------------
case ":$PATH:" in
    *":$HOME/.local/bin:"*) ;;
    *)
        log "adding ~/.local/bin to PATH in shell rc files"
        for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
            [ -f "$rc" ] || continue
            grep -qF '.local/bin' "$rc" \
                || printf '\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$rc"
        done
        ;;
esac

# --- step 6: verify -------------------------------------------------------
log "verifying installation"
if "$LAUNCHER" --version; then
    log "✅ claude --version succeeded"
    log "open a new shell (or 'source ~/.bashrc') then run: claude"
else
    die "claude --version failed — see output above"
fi
